on:
  push 

jobs:
  login_to_azure: 
    runs-on: ubuntu-latest

    steps: 
      - name: checkout code 
        uses: actions/checkout@v2
      - name: login to Azure 
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURESECRET }}
      - name: Login Confirmation
        if: success()
        run: echo "Login pass"
      - name: create resource group
        run: |          
          az group list --output table

      - name: Create App Service Plan
        run: |
          #az appservice plan create --name myappserviceplan123 --resource-group "myresourcegroup" --sku F1 --location westus

      #- name: Create the web app
        #run: az webapp create --name mywebappnew1 --resource-group "myresourcegroup" --plan myappserviceplan --runtime "NODE:18LTS"

      - name: Create a Azure vault
        run: |
          #az keyvault create --name keyvsecret920123 --resource-group "myresourcegroup" --location eastus
          az keyvault list --output table 
      
