on:
  push 

jobs:
  login_to_azure: 
    runs-on: ubuntu-latest

    steps: 
      - name: checkout code 
        uses: actions/checkout@v2
      - name: login to Azure 
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURESECRET }}
      - name: Login Confirmation
        if: success()
        run: echo "Login pass"
      - name: create resource group
        run: |
          #az group create --name "myresourcegroup" --location eastus
          az appservice plan create --name myappserviceplanrahgav --resource-group "myresourcegroup" --sku F1
          az webapp create --name mywebapp --resource-group "myresourcegroup" --plan myappserviceplan --location westus --runtime "NODE|18-lts"
 
      
